### PR TITLE
adds https support

### PR DESCRIPTION
**Pull request by gabrielcsapo**

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@echopoint thoughts on the readme and example update?

**Comment by echopoint** [comment]
Looks good, let me pull it down and check it out.

**Comment by echopoint** [comment]
We should update the index page on the documentation 
`if(type == 'upload') {` 
doesn't read as valid at this point. getType, line 246 only returns fetch, push or unknown now.

**Comment by gabrielcsapo** [comment]
@echopoint I agree, the problem is that the git client doesn't use the specific certs when making the request. This can be done via:

```
git config --global http.sslCAInfo /path/to/cert.pem
```

It doesn't look like I can do anything from the node side to fix this. The docs https://nodejs.org/api/https.html don't have any mention of being able to fix this behavior. What do you think the best course of action is?

**Comment by echopoint** [comment]
There is a way to override the ssl behavior in node, it's just not wise to do so. Basically bypassing the verification step of ssl, which is besides the point. With a self signed cert, this behavior can be overridden in the git client like we both stated, so let's document that, and not add bypasses to the server.

**Comment by gabrielcsapo** [comment]
@echopoint added doc to readme

**Comment by gabrielcsapo** [comment]
going to merge and publish under 0.4.2

**Comment by oscartbeaumont** [comment]
This is much better than my code thanks for adding https.

**Comment by gabrielcsapo** [comment]
@oscartbeaumont thank you!

**Pull request merged**
