### PR TITLE
return promise from close method if callback method not specified

### LINKED ISSUE #45: Add callback argument to close method
In order for the calling code to be properly wait for the server to shutdown, it needs to be able to pass a callback to the close method so it gets notified of the close event.

```js
await new Promise((resolve, reject) =>
  repos.close((err) => err ? reject(err) : resolve())
)
```

Currently, it's necessary to use the close method on the server property directly.

```js
await new Promise((resolve, reject) =>
  repos.server.close((err) => err ? reject(err) : resolve())
)
```

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #45

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
Awesome! @mojavelinux would you mind making close return a promise? so we can just do:

```
await server.close()
```

**Comment by mojavelinux** [comment]
I changed it so that if no callback is specified, the method returns a promise.

**Comment by gabrielcsapo** [comment]
@mojavelinux it seems like extra work to support both methods, would be able to just to keep it to returning a promise?

**Comment by mojavelinux** [comment]
Sure, I suppose. I guess that's more of a question for you. Is the goal to mimic the API of the HTTP server or simply provide a way to close the server? If the goal is just to provide a way to close the server, then we can change it to just return a promise (even though that differs from the listen API). I was just trying to be consistent.

**Comment by gabrielcsapo** [comment]
thanks!

**Pull request merged**
