### PR TITLE
Removes dependency on http-duplex package replacing w/ internal replacement lib

### PR DESCRIPTION
**Pull request by echopoint**
Examined and wrote a different version of the proxy object that http-duplex supplies without additional dependencies. Removed node's util.inherits because it seems they are looking to deprecate that way of inheriting objects. Tested locally with an 80GB repo and didn't have any issues with passing data over it. Please test and let me know of any errors. Should take care of https://github.com/gabrielcsapo/node-git-server/issues/7

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@echopoint you rock! Would you mind adding yourself to the contributors section of the package.json? I tested this locally and it is fast! Awesome!

**Comment by echopoint** [comment]
Fixed.. sorry about the extraneous commit :/

**Comment by gabrielcsapo** [comment]
@echopoint no problem! let me get this merged and published!

**Comment by gabrielcsapo** [comment]
published in https://github.com/gabrielcsapo/node-git-server/releases/tag/0.3.3 :) you rock @echopoint!

**Comment by plunkettscott** [comment]
Excellent PR!

**Pull request merged**
