### PR TITLE
makes authenticate more flexible

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- [BREAKING] changes the interface for authentication to make it more flexible
- when error is sent back to client ensure error is string

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
okay so @echopoint and @jlxip this is a breaking change, but as pointed out by @jlxip in order to make the best solution to accommodate these use cases we need to rethink authenticate and its construction. What do you guys think?

**Comment by jlxip** [comment]
How did you code that amount of code in that period of time? :laughing: 
It's 00:37 where I live. I'll have a look at this tomorrow. Great job :+1: .

**Comment by gabrielcsapo** [comment]
@jlxip haha I am in California, like I said you made the solution pretty obvious, I just rendered it to code :) Let me know what you think when you have time!

**Comment by echopoint** [comment]
@gabrielcsapo much more appropriate.

**Comment by gabrielcsapo** [comment]
@echopoint 1.0.0 release?

**Comment by echopoint** [comment]
depends, what basic feature is missing to you?

**Comment by gabrielcsapo** [comment]
@echopoint I think this kind of fixes everything we talked about before, in terms of flexibility. Everything else would be secondary to this. Do you have an items you would like added?

**Comment by echopoint** [comment]
for the basics I think that covers it.. I don't know what the target / plan is outside of this for the  project. ;)

**Comment by gabrielcsapo** [comment]
@echopoint I think my end goal for this would be getting something like https://gitea.io written on top of this. Right now I just use it to backup my stuff at home, super fast and lightweight, but lacks some administrative tooling built on top of it. I.E. mirroring, backups, issues, PR's, access-control but again I think that would be a whole different project.

**Comment by echopoint** [comment]
Then I would bump to 0.7 ;) and we can start back on the ui thread. There are so many js ui frameworks and choosing one is the fun of it.

**Comment by gabrielcsapo** [comment]
@echopoint current versions 0.3.4 should we bump to 0.4? Maybe I can add something to the readme that breaking changes are happening before 1.0.0?

**Comment by echopoint** [comment]
Adding a note to the readme about breaking changes coming would be good as a notice to be on guard.

**Comment by plunkettscott** [comment]
Another great PR. I’m still interested in the UI stuff if you want help tackling it.

**Comment by gabrielcsapo** [comment]
@plunkettscott thanks! @echopoint @plunkettscott and @jlxip let's keep the UI discussion going here https://github.com/gabrielcsapo/node-git-server/issues/12 I am going to merge and publish this.

**Comment by gabrielcsapo** [comment]
published https://github.com/gabrielcsapo/node-git-server/releases/tag/0.4.0

**Pull request merged**
