### PR TITLE
refactor authentication

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- removes authentication logic and makes it a configurable middleware

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@kubenstein this commit https://github.com/gabrielcsapo/node-git-server/pull/16/commits/0d583ca09b960cd05213e1aad00344d7d4268c75 adds that functionality.

**Comment by gabrielcsapo** [comment]
@plunkettscott anything else you might want to see in this change?

**Comment by plunkettscott** [comment]
@gabrielcsapo looks perfect. 👍

**Comment by gabrielcsapo** [comment]
@plunkettscott I am going to release this as 0.3.0, since I don't want to major version bump until the interface has been solidified.

**Comment by plunkettscott** [comment]
What other changes to the interface are you wanting to make? Or are you talking GUI?

**Comment by gabrielcsapo** [comment]
@plunkettscott I think continually finding these edge cases will help until the community as said that this is stable enough for a 1.0.0 release.

**Comment by gabrielcsapo** [comment]
@plunkettscott https://github.com/gabrielcsapo/node-git-server/releases/tag/0.3.0 release notes here

**Comment by plunkettscott** [comment]
@gabrielcsapo I'm sure in my use of this I will find more things. It would be nice to be able to namespace repos as well. Not necessarily by user (though, it could be by user if the user wanted). Something like `0.0.0.0:7005/namespace/repo.git` instead of requiring them all to be of the base domain. For my use, this could either be used to not be used. But, others it could help.

**Comment by plunkettscott** [comment]
@gabrielcsapo will review those release notes.

**Comment by gabrielcsapo** [comment]
@plunkettscott that already works right now :) If you pushed to `http://localhost:7005/plunkettscott/test.git` it will save it in the correct location!

**Comment by plunkettscott** [comment]
Ah! Didn't even know. Never tried. Is that in the documentation right now?

**Comment by gabrielcsapo** [comment]
I am not sure, but it will create the directory recursively so you could even do `http://localhost:7005/plunkettscott/anothername/continuallynaming/test.git`

**Pull request merged**
