### PR TITLE
updates docs

### PR DESCRIPTION
**Pull request by gabrielcsapo**
- adds extensive docs to Git, Util and Service
- adds named function to events to trace errors more easily

@echopoint I finally got to it! 

> this is an example of one of the events that was added to the Git class.

screen shot 2017-11-09 at 9 23 10 pm

fixes https://github.com/gabrielcsapo/node-git-server/pull/17

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@echopoint @OmgImAlexis what do you guys think?

**Comment by gabrielcsapo** [comment]
this should satisfy the original requirements of https://github.com/gabrielcsapo/node-git-server/pull/26

**Comment by echopoint** [comment]
Looks good to me.

**Comment by echopoint** [comment]
Bah spoke too soon. All http.ServerRequest type references should probably be http.IncomingMessage, depending on the context in which the variable is being assigned from. i.e. if the variable is the first parameter in the http.request event, then it should be an http.IncomingMessage instead. If the variable is assigned from the return of the http.request function, then it should be an http.ClientRequest type. ;)

http serverrequest jpg

**Comment by gabrielcsapo** [comment]
@echopoint fixed 😄

**Pull request merged**
