### PR TITLE
fixes pathing issues on non linux/unix based oses (windows)

### PR DESCRIPTION
**Pull request by echopoint**
Maybe you could use this one. I couldn't get it running on windows; thus the motivation for the change.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
Awesome @echopoint! It looks like the lint failed on the PR. Can you fix that before I merge?

**Comment by echopoint** [comment]
Didn't see the message about it failing. Sure, I'll fix it by tomorrow afternoon.

**Comment by echopoint** [comment]
Ok. There we go.

**Comment by gabrielcsapo** [comment]
@echopoint thank you! Will merge and update this with the release it was published in.

**Comment by gabrielcsapo** [comment]
@echopoint published in https://github.com/gabrielcsapo/node-git-server/releases/tag/0.3.2

**Pull request merged**
