### PR TITLE
documentation and initial tests for duplexing lib

### PR DESCRIPTION
**Pull request by echopoint**
This should help on issue #6 and #17 and document the HttpDuplex class. This can sit and wait for other docs to be wrapped into the next release as well.

### CODE REVIEW

**Comment by gabrielcsapo** [comment]
@echopoint is this good to go? :) I will generate the JSdoc when this gets merged. I have some code waiting to be submitted, just keep getting side tracked.

**Comment by echopoint** [comment]
should be.. and no worries just throwing stuff in when I get the time/chance

**Comment by gabrielcsapo** [comment]
docs updated and pushed @echopoint https://www.gabrielcsapo.com/node-git-server/code/HttpDuplex.html

**Comment by echopoint** [comment]
Yup looks, ok, Only thing I noticed working on that doc is multiple '@see' references in the comments don't line up, but eh, on the grand scale o' things that's ok atm.

**Comment by gabrielcsapo** [comment]
@echopoint is that a css bug? can you screenshot and post here?

**Comment by echopoint** [comment]
Most likely a css bug since the html generated is basic and the links are just links inside of a ul.

screenshot 1 jpg

**Comment by gabrielcsapo** [comment]
ohhh, yeah it is a bug, the see tag has a fixed width. 

screen shot 2017-11-08 at 9 21 31 pm

**Comment by echopoint** [comment]
Looks to me because see is float: left causes the issue. If the block the label was in was a hard left block vertically spanning a full column, the problem would go away and it would align up.

see-floating-left2 jpg

**Comment by gabrielcsapo** [comment]
simply removing this arbitrary width seems to fix the problem, I don't now if this was purposeful as it seems to align things specifically with the intention of only one see existing at a time.

screen shot 2017-11-08 at 9 54 22 pm

**Comment by echopoint** [comment]
Simpler is always better. So fine with me. I'll get around to looking at the css for the theme in a couple of days. ;)

**Comment by gabrielcsapo** [comment]
I submitted a quick PR, it seems unmaintained but hoping for the best.

**Comment by echopoint** [comment]
bah, been a year.. may have to pull an actionhero there but we'll see.

**Comment by gabrielcsapo** [comment]
could switch templates https://github.com/nijikokun/minami, I have used this before. Or what if we just don't have a theme? 

screen shot 2017-11-08 at 10 15 43 pm
screen shot 2017-11-08 at 10 15 38 pm

**Comment by echopoint** [comment]
Out of the two I'd probably pick minami as plan b. Themes don't get much attention once they're in the wild.

**Comment by gabrielcsapo** [comment]
@echopoint so you are saying stick with no theme?

**Comment by echopoint** [comment]
I'm fine with any of the choices really. It's documentation. Readability is king there, and they are all readable. I'm a fairly simple person in that respect. The final answer is ultimately up to you. ;)

**Comment by gabrielcsapo** [comment]
Okay let me fix up my docs, send a PR and we can flip a coin 😄

**Pull request merged**
